server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}

logging:
  level:
    com.services: DEBUG

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
        allowed-methods: "GET,POST"
    beans:
      cache:
        time-to-live: "10s"
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

spring:
  messages:
    basename: messages

pixabay:
  key: ${PIXABAY_KEY}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
