server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  main:
    locale: ko_KR
  messages:
    basename: messages
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    data:
      web:
        pageable:
          default-page-size: 20

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

pixabay:
  key: ${PIXABAY_KEY}
  url:
    video: ${PIXABAY_VIDEO_URL}
    music: ${PIXABAY_MUSIC_URL}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

cloudflare:
  r2:
    token:
    access-key:
    secret-key:
    endpoint:
    bucket-name: