server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: api
  main:
    locale: ko_KR
  messages:
    basename: messages
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    data:
      web:
        pageable:
          default-page-size: 20
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: ${OMNIWATCH_DB_URL:jdbc:h2:mem:testdb}
    username: ${OMNIWATCH_DB_USERNAME:sa}
    password: ${OMNIWATCH_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

cloudflare:
  r2:
    token:
    access-key:
    secret-key:
    endpoint:
    bucket-name:

logging:
  level:
    com.services: INFO
